// Gazetteer of the Acts of the Apostles. Coordinates are the modern WGS-84
// positions of the identified (or most widely accepted candidate) sites;
// elevations are metres above mean sea level.

export type Kind = 'acts' | 'city' | 'port';
export type Theme = '初期教会' | '第一程' | '第二程' | '第三程' | '赴罗马' | '背景';

export type Place = {
  id: string;
  name: string;      // 中文
  greek: string;     // 一世纪名称
  site?: string;     // 今址
  lon: number;
  lat: number;
  elev: number;
  region: string;
  kind: Kind;
  theme: Theme;
  date?: string;
  title?: string;
  description?: string;
  reference?: string;
};

export const places: Place[] = [
  // ——— 犹太、撒马利亚、叙利亚：使徒行传 1–12 ———
  { id: 'jerusalem', name: '耶路撒冷', greek: 'ΙΕΡΟΥΣΑΛΗΜ', site: 'Jerusalem', lon: 35.2345, lat: 31.7784, elev: 754,
    region: '犹太', kind: 'acts', theme: '初期教会', date: '约公元 30–57 年', title: '从这里开始',
    description: '全书的起点与轴心。五旬节的火焰、最初的团契、司提反的殉道、耶路撒冷会议，都发生在这座海拔七百多米的山城。保罗三次宣教旅程都以回到这里为终点，最后一次回来即被捕。',
    reference: '使徒行传 1:8；2:1–41；15:1–35；21:17–36' },
  { id: 'olivet', name: '橄榄山', greek: 'ΕΛΑΙΩΝ', site: 'Mount of Olives', lon: 35.2540, lat: 31.7780, elev: 826,
    region: '犹太', kind: 'acts', theme: '初期教会', date: '公元 30 年', title: '升天与差遣',
    description: '距耶路撒冷一个安息日的路程。门徒在此领受「直到地极」的差遣，全书余下的地理就是这句话的展开。',
    reference: '使徒行传 1:9–12' },
  { id: 'samaria', name: '撒马利亚', greek: 'ΣΕΒΑΣΤΗ', site: 'Sebastia', lon: 35.1950, lat: 32.2770, elev: 440,
    region: '撒马利亚', kind: 'acts', theme: '初期教会', date: '约公元 33 年', title: '福音出犹太',
    description: '司提反殉道后教会四散，腓利下到撒马利亚城传道，行邪术的西门在此受洗。这是福音第一次越过犹太人的边界。',
    reference: '使徒行传 8:4–25' },
  { id: 'gaza', name: '迦萨', greek: 'ΓΑΖΑ', site: 'Gaza', lon: 34.4667, lat: 31.5167, elev: 45,
    region: '犹太', kind: 'acts', theme: '初期教会', date: '约公元 33 年', title: '旷野的路上',
    description: '从耶路撒冷下迦萨的路穿过旷野。腓利在这条路上遇见埃塞俄比亚太监，福音由此指向非洲。',
    reference: '使徒行传 8:26–39' },
  { id: 'azotus', name: '亚锁都', greek: 'ΑΖΩΤΟΣ', site: 'Ashdod', lon: 34.6500, lat: 31.7500, elev: 40,
    region: '犹太', kind: 'acts', theme: '初期教会', title: '腓利的沿海路线',
    description: '腓利为太监施洗后，被提到亚锁都，沿海岸一路传福音直到该撒利亚。',
    reference: '使徒行传 8:40' },
  { id: 'lydda', name: '吕大', greek: 'ΛΥΔΔΑ', site: 'Lod', lon: 34.8900, lat: 31.9500, elev: 60,
    region: '犹太', kind: 'acts', theme: '初期教会', title: '以尼雅起来',
    description: '沿海平原与山地之间的路口小城。彼得在此医治瘫痪八年的以尼雅。',
    reference: '使徒行传 9:32–35' },
  { id: 'joppa', name: '约帕', greek: 'ΙΟΠΠΗ', site: 'Jaffa', lon: 34.7550, lat: 32.0500, elev: 30,
    region: '犹太', kind: 'port', theme: '初期教会', date: '约公元 38 年', title: '屋顶上的异象',
    description: '犹太人的老港口。彼得在硝皮匠西门家的屋顶上看见那块降下的大布，随后动身去外邦人哥尼流家——教会的门槛在这里被挪开。',
    reference: '使徒行传 9:36–43；10:9–23' },
  { id: 'caesarea', name: '该撒利亚', greek: 'ΚΑΙΣΑΡΕΙΑ', site: 'Caesarea Maritima', lon: 34.8917, lat: 32.5000, elev: 5,
    region: '犹太', kind: 'port', theme: '初期教会', date: '公元 40–59 年', title: '罗马的门户',
    description: '希律大帝建的人工深水港，罗马巡抚的驻地。哥尼流在此受洗，腓利在此定居，保罗在此被囚两年，最后从这里上船去罗马。',
    reference: '使徒行传 10:1–48；21:8；23:23–26:32' },
  { id: 'antipatris', name: '安提帕底', greek: 'ΑΝΤΙΠΑΤΡΙΣ', site: 'Tel Afek', lon: 34.9350, lat: 32.1030, elev: 40,
    region: '犹太', kind: 'city', theme: '初期教会',
    description: '罗马兵连夜押送保罗从耶路撒冷到该撒利亚，中途在此换班。',
    reference: '使徒行传 23:31' },
  { id: 'damascus', name: '大马色', greek: 'ΔΑΜΑΣΚΟΣ', site: 'Damascus', lon: 36.3060, lat: 33.5130, elev: 690,
    region: '叙利亚', kind: 'acts', theme: '初期教会', date: '约公元 34 年', title: '路上的光',
    description: '沙漠边缘的绿洲大城，也是全书的转折点。扫罗在近城的路上被光照倒，三日不能看见；亚拿尼亚为他按手，他从筐子里缒城而逃。',
    reference: '使徒行传 9:1–25；22:6–16；26:12–18' },
  { id: 'antioch-syria', name: '安提阿', greek: 'ΑΝΤΙΟΧΕΙΑ', site: 'Antakya', lon: 36.1600, lat: 36.2000, elev: 85,
    region: '叙利亚', kind: 'acts', theme: '初期教会', date: '公元 40 年代起', title: '外邦宣教的母会',
    description: '帝国第三大城，人口约五十万。门徒在这里第一次被称为「基督徒」。三次宣教旅程都从这座城出发，也都回到这里述职。',
    reference: '使徒行传 11:19–26；13:1–3；14:26–28；15:35；18:22–23' },
  { id: 'seleucia', name: '西流基', greek: 'ΣΕΛΕΥΚΕΙΑ', site: 'Samandağ', lon: 35.9300, lat: 36.1200, elev: 10,
    region: '叙利亚', kind: 'port', theme: '第一程', title: '起航的港',
    description: '安提阿的外港，在奥龙特斯河口。第一次宣教旅程从这里下船。',
    reference: '使徒行传 13:4' },
  { id: 'tarsus', name: '大数', greek: 'ΤΑΡΣΟΣ', site: 'Tarsus', lon: 34.8950, lat: 36.9170, elev: 20,
    region: '基利家', kind: 'acts', theme: '初期教会', title: '保罗的本乡',
    description: '基利家的首府、著名的学术之城，也是保罗生长之地。他从耶路撒冷避难回到这里，多年后由巴拿巴找来同去安提阿。',
    reference: '使徒行传 9:30；11:25–26；21:39；22:3' },
  { id: 'ptolemais', name: '多利买', greek: 'ΠΤΟΛΕΜΑΙΣ', site: 'Acre', lon: 35.0700, lat: 32.9280, elev: 10,
    region: '犹太', kind: 'port', theme: '第三程',
    description: '腓尼基南端的良港。保罗末次上耶路撒冷时在此停留一日。',
    reference: '使徒行传 21:7' },
  { id: 'tyre', name: '推罗', greek: 'ΤΥΡΟΣ', site: 'Sour', lon: 35.1950, lat: 33.2700, elev: 10,
    region: '叙利亚', kind: 'port', theme: '第三程', title: '沙滩上的送别',
    description: '腓尼基的古老海港。船在此卸货七日，门徒和妻子儿女送保罗到城外，众人在沙滩上跪下祷告。',
    reference: '使徒行传 21:3–6' },
  { id: 'sidon', name: '西顿', greek: 'ΣΙΔΩΝ', site: 'Saida', lon: 35.3720, lat: 33.5600, elev: 15,
    region: '叙利亚', kind: 'port', theme: '赴罗马',
    description: '押送保罗的船离开该撒利亚后的第一站。百夫长犹流准他上岸见朋友。',
    reference: '使徒行传 27:3' },

  // ——— 第一次宣教旅程：使徒行传 13–14 ———
  { id: 'salamis', name: '撒拉米', greek: 'ΣΑΛΑΜΙΣ', site: 'Famagusta 近郊', lon: 33.9000, lat: 35.1800, elev: 5,
    region: '居比路', kind: 'acts', theme: '第一程', date: '约公元 47 年',
    description: '居比路岛东岸的大城。巴拿巴的家乡在这座岛上，第一次旅程从这里的犹太会堂开讲。',
    reference: '使徒行传 13:5' },
  { id: 'paphos', name: '帕弗', greek: 'ΠΑΦΟΣ', site: 'Paphos', lon: 32.4060, lat: 34.7570, elev: 15,
    region: '居比路', kind: 'acts', theme: '第一程', title: '方伯归信',
    description: '居比路的省会。行法术的以吕马受责成了瞎子，方伯士求保罗信了道。从这一章起，路加改称扫罗为「保罗」，叙事的主角也换了人。',
    reference: '使徒行传 13:6–12' },
  { id: 'perga', name: '别加', greek: 'ΠΕΡΓΗ', site: 'Perge', lon: 30.8540, lat: 36.9610, elev: 40,
    region: '旁非利亚', kind: 'acts', theme: '第一程', title: '马可离队之处',
    description: '旁非利亚的内陆城。约翰马可在此离开他们回耶路撒冷，这件事后来让保罗与巴拿巴分道。',
    reference: '使徒行传 13:13；15:38' },
  { id: 'antioch-pisidia', name: '彼西底的安提阿', greek: 'ΑΝΤΙΟΧΕΙΑ ΠΙΣΙΔΙΑΣ', site: 'Yalvaç', lon: 31.1830, lat: 38.3060, elev: 1200,
    region: '加拉太', kind: 'acts', theme: '第一程', date: '约公元 47 年', title: '转向外邦人',
    description: '海拔一千二百米的罗马殖民城，从别加上来要翻越陶鲁斯山。保罗在会堂里讲了全书最长的一篇道，被赶出城后说：「我们就转向外邦人去。」',
    reference: '使徒行传 13:14–52' },
  { id: 'iconium', name: '以哥念', greek: 'ΙΚΟΝΙΟΝ', site: 'Konya', lon: 32.4930, lat: 37.8710, elev: 1030,
    region: '加拉太', kind: 'acts', theme: '第一程',
    description: '安纳托利亚高原上的会堂之城。二人在此住了多日，直到城里的人要用石头打他们才离开。',
    reference: '使徒行传 14:1–7' },
  { id: 'lystra', name: '路司得', greek: 'ΛΥΣΤΡΑ', site: 'Hatunsaray', lon: 32.4530, lat: 37.5800, elev: 1150,
    region: '加拉太', kind: 'acts', theme: '第一程', title: '被当作神，又被石头打',
    description: '瘸腿的人被医好，众人以为宙斯和赫耳墨斯降临，要献牛给他们；几日后同一群人用石头把保罗打得拖出城外。提摩太的家在这里。',
    reference: '使徒行传 14:8–20；16:1–3' },
  { id: 'derbe', name: '特庇', greek: 'ΔΕΡΒΗ', site: 'Kerti Höyük', lon: 33.3400, lat: 37.3500, elev: 1150,
    region: '加拉太', kind: 'acts', theme: '第一程',
    description: '第一次旅程最东的一站。传了福音、门徒众多之后，二人不走近路回大数，而是原路折返坚固各教会。',
    reference: '使徒行传 14:20–23' },
  { id: 'attalia', name: '亚大利', greek: 'ΑΤΤΑΛΕΙΑ', site: 'Antalya', lon: 30.7000, lat: 36.8850, elev: 30,
    region: '旁非利亚', kind: 'port', theme: '第一程',
    description: '旁非利亚的主要海港，第一次旅程由此坐船回安提阿。',
    reference: '使徒行传 14:25–26' },

  // ——— 第二次宣教旅程：使徒行传 15:36–18:22 ———
  { id: 'troas', name: '特罗亚', greek: 'ΤΡΩΑΣ', site: 'Dalyan 遗址', lon: 26.1590, lat: 39.7500, elev: 30,
    region: '亚细亚', kind: 'port', theme: '第二程', date: '约公元 50 年', title: '马其顿的异象',
    description: '爱琴海东岸的罗马殖民港。保罗夜间看见马其顿人求他过去帮助——福音由此跨过爱琴海进入欧洲。路加的叙述也在这里第一次改用「我们」。',
    reference: '使徒行传 16:8–11；20:5–12' },
  { id: 'samothrace', name: '撒摩特喇', greek: 'ΣΑΜΟΘΡΑΚΗ', site: 'Samothraki', lon: 25.5300, lat: 40.4500, elev: 300,
    region: '爱琴海', kind: 'port', theme: '第二程',
    description: '爱琴海北部的高耸岛屿，过海的船在此停一夜。',
    reference: '使徒行传 16:11' },
  { id: 'neapolis', name: '尼亚波利', greek: 'ΝΕΑΠΟΛΙΣ', site: 'Kavala', lon: 24.4100, lat: 40.9400, elev: 15,
    region: '马其顿', kind: 'port', theme: '第二程', title: '踏上欧洲',
    description: '腓立比的外港，也是福音登上欧洲大陆的第一个落点。',
    reference: '使徒行传 16:11' },
  { id: 'philippi', name: '腓立比', greek: 'ΦΙΛΙΠΠΟΙ', site: 'Filippoi', lon: 24.2870, lat: 41.0130, elev: 110,
    region: '马其顿', kind: 'acts', theme: '第二程', date: '约公元 50 年', title: '河边与狱中',
    description: '罗马退伍军人的殖民城，城里犹太人少到没有会堂。卖紫色布的吕底亚在河边信主；保罗和西拉被打入监，半夜唱诗时地大震动，禁卒全家受洗。',
    reference: '使徒行传 16:12–40' },
  { id: 'amphipolis', name: '暗妃波里', greek: 'ΑΜΦΙΠΟΛΙΣ', site: 'Amfipoli', lon: 23.8420, lat: 40.8200, elev: 60,
    region: '马其顿', kind: 'city', theme: '第二程',
    description: '厄格那提大道上的驿站城，二人经过而未停留。',
    reference: '使徒行传 17:1' },
  { id: 'apollonia', name: '亚波罗尼亚', greek: 'ΑΠΟΛΛΩΝΙΑ', site: 'Apollonia', lon: 23.4400, lat: 40.6200, elev: 90,
    region: '马其顿', kind: 'city', theme: '第二程',
    description: '厄格那提大道上的另一站，同样只是路过。',
    reference: '使徒行传 17:1' },
  { id: 'thessalonica', name: '帖撒罗尼迦', greek: 'ΘΕΣΣΑΛΟΝΙΚΗ', site: 'Thessaloniki', lon: 22.9440, lat: 40.6400, elev: 20,
    region: '马其顿', kind: 'acts', theme: '第二程', title: '「搅乱天下的」',
    description: '马其顿的省会与大港。保罗一连三个安息日在会堂辩论，城里骚动，控告他们说「那搅乱天下的也到这里来了」。',
    reference: '使徒行传 17:1–9' },
  { id: 'berea', name: '庇哩亚', greek: 'ΒΕΡΟΙΑ', site: 'Veria', lon: 22.2020, lat: 40.5240, elev: 180,
    region: '马其顿', kind: 'acts', theme: '第二程', title: '天天考查圣经',
    description: '奥林匹斯山北麓的小城。这里的人被称为比帖撒罗尼迦人更贤明，因为他们甘心领受，还天天查考圣经。',
    reference: '使徒行传 17:10–14' },
  { id: 'athens', name: '雅典', greek: 'ΑΘΗΝΑΙ', site: 'Athens', lon: 23.7280, lat: 37.9720, elev: 100,
    region: '亚该亚', kind: 'acts', theme: '第二程', date: '约公元 51 年', title: '亚略巴古的讲论',
    description: '哲学之城，政治上已经衰落。保罗见满城的偶像心里着急，在亚略巴古从「未识之神」的坛讲起，是全书唯一一篇对纯外邦听众的讲论。',
    reference: '使徒行传 17:16–34' },
  { id: 'corinth', name: '哥林多', greek: 'ΚΟΡΙΝΘΟΣ', site: 'Korinthos', lon: 22.8850, lat: 37.9060, elev: 90,
    region: '亚该亚', kind: 'acts', theme: '第二程', date: '公元 50–52 年', title: '住了一年零六个月',
    description: '扼守地峡的双港商城，亚该亚省会。保罗与亚居拉、百基拉一同做帐棚，在此停留一年半——全程最长的一次驻留。方伯迦流拒绝受理对他的控告，这条铭文也成了新约年代学的定点。',
    reference: '使徒行传 18:1–18' },
  { id: 'cenchreae', name: '坚革哩', greek: 'ΚΕΓΧΡΕΑΙ', site: 'Kechries', lon: 22.9880, lat: 37.8870, elev: 5,
    region: '亚该亚', kind: 'port', theme: '第二程',
    description: '哥林多的东港。保罗在这里剪了头发还愿，然后开船去叙利亚。',
    reference: '使徒行传 18:18' },

  // ——— 第三次宣教旅程：使徒行传 18:23–21:17 ———
  { id: 'ephesus', name: '以弗所', greek: 'ΕΦΕΣΟΣ', site: 'Selçuk', lon: 27.3400, lat: 37.9400, elev: 20,
    region: '亚细亚', kind: 'acts', theme: '第三程', date: '公元 52–55 年', title: '银匠的暴动',
    description: '亚细亚省的首城，亚底米神庙所在地。保罗在推喇奴的学房天天辩论两年，全亚细亚都听见了主的道；银匠底米丢煽动的暴乱把满城人挤进两万五千座的剧场。',
    reference: '使徒行传 19:1–41' },
  { id: 'assos', name: '亚朔', greek: 'ΑΣΣΟΣ', site: 'Behramkale', lon: 26.3360, lat: 39.4900, elev: 200,
    region: '亚细亚', kind: 'port', theme: '第三程',
    description: '保罗独自从特罗亚步行三十公里翻山到此，再上船与同伴会合。',
    reference: '使徒行传 20:13–14' },
  { id: 'mitylene', name: '米推利尼', greek: 'ΜΙΤΥΛΗΝΗ', site: 'Mytilene', lon: 26.5540, lat: 39.1100, elev: 20,
    region: '爱琴海', kind: 'port', theme: '第三程',
    description: '列斯波岛的主城，沿岸南下的一夜停泊处。',
    reference: '使徒行传 20:14' },
  { id: 'chios', name: '基阿', greek: 'ΧΙΟΣ', site: 'Chios', lon: 26.1360, lat: 38.3680, elev: 20,
    region: '爱琴海', kind: 'port', theme: '第三程',
    description: '爱琴海东侧的大岛，船在对面抛锚过夜。',
    reference: '使徒行传 20:15' },
  { id: 'samos', name: '撒摩', greek: 'ΣΑΜΟΣ', site: 'Samos', lon: 26.9760, lat: 37.7550, elev: 20,
    region: '爱琴海', kind: 'port', theme: '第三程',
    description: '与小亚细亚海岸只隔一条窄水道的岛，南下的第三夜。',
    reference: '使徒行传 20:15' },
  { id: 'miletus', name: '米利都', greek: 'ΜΙΛΗΤΟΣ', site: 'Balat', lon: 27.2770, lat: 37.5300, elev: 10,
    region: '亚细亚', kind: 'acts', theme: '第三程', title: '与以弗所长老诀别',
    description: '保罗为赶在五旬节前到耶路撒冷而越过以弗所，把长老请到这里。这是他在全书中唯一一次对教会领袖讲话，说完就跪下同众人祷告，众人抱着他的颈项与他亲嘴。',
    reference: '使徒行传 20:15–38' },
  { id: 'cos', name: '哥士', greek: 'ΚΩΣ', site: 'Kos', lon: 27.2880, lat: 36.8930, elev: 10,
    region: '爱琴海', kind: 'port', theme: '第三程',
    description: '离开米利都后一路直行的第一站。',
    reference: '使徒行传 21:1' },
  { id: 'rhodes', name: '罗底', greek: 'ΡΟΔΟΣ', site: 'Rhodes', lon: 28.2270, lat: 36.4510, elev: 25,
    region: '爱琴海', kind: 'port', theme: '第三程',
    description: '东地中海的老牌航运岛，往叙利亚的航路必经。',
    reference: '使徒行传 21:1' },
  { id: 'patara', name: '帕大喇', greek: 'ΠΑΤΑΡΑ', site: 'Patara', lon: 29.3160, lat: 36.2620, elev: 10,
    region: '吕家', kind: 'port', theme: '第三程', title: '换乘远洋船',
    description: '吕家的大港。保罗一行在此换上直航腓尼基的大船，离开沿岸跳岛的小船，横渡开阔海面。',
    reference: '使徒行传 21:1–2' },

  // ——— 押解赴罗马：使徒行传 27–28 ———
  { id: 'myra', name: '每拉', greek: 'ΜΥΡΑ', site: 'Demre', lon: 29.9850, lat: 36.2580, elev: 25,
    region: '吕家', kind: 'port', theme: '赴罗马', title: '换上运麦的船',
    description: '埃及运粮船北上的固定停靠港。百夫长在此找到一只亚历山大来的船，把囚犯换上去。',
    reference: '使徒行传 27:5–6' },
  { id: 'cnidus', name: '革尼土', greek: 'ΚΝΙΔΟΣ', site: 'Knidos', lon: 27.3740, lat: 36.6870, elev: 15,
    region: '亚细亚', kind: 'port', theme: '赴罗马',
    description: '小亚细亚西南角的岬角港。船行得慢，到这里已经被逆风顶住。',
    reference: '使徒行传 27:7' },
  { id: 'salmone', name: '撒摩尼', greek: 'ΣΑΛΜΩΝΗ', site: 'Cape Sideros', lon: 26.3000, lat: 35.2900, elev: 30,
    region: '革哩底', kind: 'port', theme: '赴罗马',
    description: '革哩底岛东端的海角，船绕过它到背风的南岸。',
    reference: '使徒行传 27:7' },
  { id: 'fair-havens', name: '佳澳', greek: 'ΚΑΛΟΙ ΛΙΜΕΝΕΣ', site: 'Kali Limenes', lon: 24.8000, lat: 34.9300, elev: 10,
    region: '革哩底', kind: 'acts', theme: '赴罗马', title: '被否决的忠告',
    description: '革哩底南岸的小湾，靠近拉西亚城。禁食的节期已过，航行有险，保罗劝他们就地过冬；百夫长信从船主，不信保罗。',
    reference: '使徒行传 27:8–12' },
  { id: 'phoenix', name: '非尼基', greek: 'ΦΟΙΝΙΞ', site: 'Loutro', lon: 24.0800, lat: 35.2000, elev: 10,
    region: '革哩底', kind: 'port', theme: '赴罗马',
    description: '他们想赶去过冬的良港，却在半路遇上「友拉革罗」的狂风。',
    reference: '使徒行传 27:12–14' },
  { id: 'clauda', name: '高大', greek: 'ΚΛΑΥΔΑ', site: 'Gavdos', lon: 24.0800, lat: 34.8400, elev: 100,
    region: '革哩底', kind: 'acts', theme: '赴罗马', title: '风暴中的小岛',
    description: '风暴中船贴着这座小岛的背风面掠过，水手趁机收起救生的小船，用缆索捆住船底。此后十四天在海上漂来漂去。',
    reference: '使徒行传 27:16–17' },
  { id: 'malta', name: '米利大', greek: 'ΜΕΛΙΤΗ', site: 'Malta', lon: 14.4200, lat: 35.8900, elev: 60,
    region: '米利大', kind: 'acts', theme: '赴罗马', date: '约公元 60 年冬', title: '船破人存',
    description: '漂流十四天后触礁的岛，二百七十六人无一丧命。岛上土人生火接待他们，保罗被毒蛇咬却无害，又医好岛长父亲的病。全船在此过冬三个月。',
    reference: '使徒行传 27:39–28:11' },
  { id: 'syracuse', name: '叙拉古', greek: 'ΣΥΡΑΚΟΥΣΑΙ', site: 'Siracusa', lon: 15.2930, lat: 37.0750, elev: 20,
    region: '西西里', kind: 'port', theme: '赴罗马',
    description: '西西里东岸的大港，开春后北上的第一站，停了三天。',
    reference: '使徒行传 28:12' },
  { id: 'rhegium', name: '利基翁', greek: 'ΡΗΓΙΟΝ', site: 'Reggio Calabria', lon: 15.6500, lat: 38.1100, elev: 30,
    region: '意大利', kind: 'port', theme: '赴罗马',
    description: '墨西拿海峡口的港。等到南风起，一天一夜就到了部丢利。',
    reference: '使徒行传 28:13' },
  { id: 'puteoli', name: '部丢利', greek: 'ΠΟΤΙΟΛΟΙ', site: 'Pozzuoli', lon: 14.1210, lat: 40.8230, elev: 30,
    region: '意大利', kind: 'port', theme: '赴罗马', title: '登陆意大利',
    description: '罗马的粮食门户，那不勒斯湾内的大港。保罗在此遇见弟兄，被请住了七天，之后走亚比乌大道进京。',
    reference: '使徒行传 28:13–14' },
  { id: 'appii-forum', name: '亚比乌市', greek: 'ΑΠΠΙΟΥ ΦΟΡΟΝ', site: 'Borgo Faiti', lon: 12.9700, lat: 41.4400, elev: 10,
    region: '意大利', kind: 'city', theme: '赴罗马', title: '罗马的弟兄迎上来',
    description: '亚比乌大道上距罗马六十公里的驿站。罗马的弟兄听见消息，一路走到这里迎接，保罗见了就感谢神，放心壮胆。',
    reference: '使徒行传 28:15' },
  { id: 'three-taverns', name: '三馆', greek: 'ΤΡΕΙΣ ΤΑΒΕΡΝΑΙ', site: 'Cisterna 附近', lon: 12.8300, lat: 41.5900, elev: 80,
    region: '意大利', kind: 'city', theme: '赴罗马',
    description: '大道上更近罗马的一站，另一批弟兄在这里等他。',
    reference: '使徒行传 28:15' },
  { id: 'rome', name: '罗马', greek: 'ΡΩΜΗ', site: 'Roma', lon: 12.4823, lat: 41.8930, elev: 40,
    region: '意大利', kind: 'acts', theme: '赴罗马', date: '约公元 60–62 年', title: '放胆传讲，无人禁止',
    description: '全书的终点，也是「直到地极」的象征。保罗自费租房住了两年，戴着锁链接待所有来见他的人。路加没有写他的结局，只写福音在帝国的心脏毫无拦阻地传开。',
    reference: '使徒行传 28:16–31' },

  // ——— 背景：书中提到、未曾亲历的地方 ———
  { id: 'thyatira', name: '推雅推喇', greek: 'ΘΥΑΤΕΙΡΑ', site: 'Akhisar', lon: 27.8400, lat: 38.9200, elev: 100,
    region: '亚细亚', kind: 'city', theme: '背景',
    description: '以染紫布著称的城，吕底亚的家乡；她在腓立比河边成了欧洲第一位信徒。',
    reference: '使徒行传 16:14' },
  { id: 'adramyttium', name: '亚大米田', greek: 'ΑΔΡΑΜΥΤΤΙΟΝ', site: 'Edremit', lon: 27.0200, lat: 39.5900, elev: 20,
    region: '亚细亚', kind: 'city', theme: '背景',
    description: '载保罗离开该撒利亚的第一艘船的船籍港。',
    reference: '使徒行传 27:2' },
  { id: 'alexandria', name: '亚历山大', greek: 'ΑΛΕΞΑΝΔΡΕΙΑ', site: 'Alexandria', lon: 29.9187, lat: 31.2001, elev: 5,
    region: '埃及', kind: 'city', theme: '背景',
    description: '帝国的粮仓与犹太学术重镇。亚波罗从这里来，载保罗去意大利的两艘运粮船也都属于这座港。',
    reference: '使徒行传 18:24；27:6；28:11' },
  { id: 'cyrene', name: '古利奈', greek: 'ΚΥΡΗΝΗ', site: 'Shahhat', lon: 21.8600, lat: 32.8250, elev: 600,
    region: '古利奈', kind: 'city', theme: '背景',
    description: '北非的希腊化城市，有很大的犹太侨民社群。最早向外邦希利尼人传福音的，正是古利奈人与居比路人。',
    reference: '使徒行传 2:10；11:20；13:1' },
  { id: 'byzantium', name: '拜占庭', greek: 'ΒΥΖΑΝΤΙΟΝ', site: 'Istanbul', lon: 28.9784, lat: 41.0082, elev: 40,
    region: '庇推尼', kind: 'city', theme: '背景',
    description: '博斯普鲁斯海峡口的城。保罗第二次旅程想往庇推尼去，「耶稣的灵却不许」，路线因此折向特罗亚与欧洲。',
    reference: '使徒行传 16:7' },
  { id: 'ancyra', name: '安该拉', greek: 'ΑΓΚΥΡΑ', site: 'Ankara', lon: 32.8600, lat: 39.9300, elev: 900,
    region: '加拉太', kind: 'city', theme: '背景',
    description: '加拉太省的首府。保罗两次「走遍加拉太和弗吕家一带地方」，坚固众门徒。',
    reference: '使徒行传 16:6；18:23' },
];

export const themes = ['全部', '初期教会', '第一程', '第二程', '第三程', '赴罗马', '背景'] as const;
export type ThemeFilter = (typeof themes)[number];

// ---------------------------------------------------------------- journeys

export type JourneyKey = 'first' | 'second' | 'third' | 'rome';

/**
 * Paul's itineraries, as sequences of gazetteer ids. Keeping them as ids rather
 * than coordinates means a route can never drift away from the marker it runs
 * through, and the renderer drapes the legs over the terrain — a sea crossing
 * lies flat at 0 m because that is what the DEM says the sea is.
 *
 * Acts names the stops, not the tracks. Overland legs follow the Roman road
 * that joined the two towns and sea legs the shortest sensible course, so read
 * the lines as the order of travel rather than as surveyed routes.
 */
export const journeys: {
  key: JourneyKey; name: string; note: string; reference: string; stops: string[];
}[] = [
  {
    key: 'first', name: '第一次宣教旅程', note: '约公元 46–48 年 · 居比路与加拉太南部',
    reference: '使徒行传 13–14',
    stops: [
      'antioch-syria', 'seleucia', 'salamis', 'paphos', 'perga', 'antioch-pisidia',
      'iconium', 'lystra', 'derbe', 'lystra', 'iconium', 'antioch-pisidia', 'perga',
      'attalia', 'seleucia', 'antioch-syria',
    ],
  },
  {
    key: 'second', name: '第二次宣教旅程', note: '约公元 49–52 年 · 福音进入欧洲',
    reference: '使徒行传 15:36–18:22',
    stops: [
      'antioch-syria', 'tarsus', 'derbe', 'lystra', 'iconium', 'antioch-pisidia',
      'troas', 'samothrace', 'neapolis', 'philippi', 'amphipolis', 'apollonia',
      'thessalonica', 'berea', 'athens', 'corinth', 'cenchreae', 'ephesus',
      'caesarea', 'jerusalem', 'antioch-syria',
    ],
  },
  {
    key: 'third', name: '第三次宣教旅程', note: '约公元 53–57 年 · 以弗所的三年',
    reference: '使徒行传 18:23–21:17',
    stops: [
      'antioch-syria', 'tarsus', 'ancyra', 'ephesus', 'troas', 'philippi',
      'thessalonica', 'berea', 'corinth', 'philippi', 'troas', 'assos', 'mitylene',
      'chios', 'samos', 'miletus', 'cos', 'rhodes', 'patara', 'tyre', 'ptolemais',
      'caesarea', 'jerusalem',
    ],
  },
  {
    key: 'rome', name: '押解赴罗马', note: '约公元 59–60 年 · 一场海难与一次上诉',
    reference: '使徒行传 27–28',
    stops: [
      'caesarea', 'sidon', 'myra', 'cnidus', 'salmone', 'fair-havens', 'clauda',
      'malta', 'syracuse', 'rhegium', 'puteoli', 'appii-forum', 'three-taverns', 'rome',
    ],
  },
];
