// Fetches the elevation grid behind the map and writes app/dem.ts.
//
//     node scripts/build-dem.mjs
//
// Source: NASA SRTM 90 m via the public OpenTopoData API, sampled on a 0.1°
// (~11 km) grid over the eastern Mediterranean. That is coarse, but the frame is
// 26° wide — this map is about the shape of a sea and the coasts around it, not
// about single hillsides.
//
// SRTM is a land model: it reports open water as null, which is written out as 0
// and is what the renderer uses as its sea mask. Land that genuinely sits below
// sea level would be swallowed by the same rule, so everything outside the
// Jordan rift is floored at 1 m — the Dead Sea and the Sea of Galilee stay real
// water, the Qattara Depression on the southern edge of the frame does not turn
// into a lake.
//
// The public endpoint allows one call a second, so the run takes about six
// minutes. It is polite to their server and it only has to happen when the grid
// changes.
import { writeFileSync } from 'node:fs';

const BOUNDS = { w: 11.5, e: 37.5, s: 30.0, n: 42.5 };
const STEP = 0.1;
const NX = Math.round((BOUNDS.e - BOUNDS.w) / STEP) + 1;
const NY = Math.round((BOUNDS.n - BOUNDS.s) / STEP) + 1;

/** Where a negative elevation is real water rather than a dry depression. */
const RIFT = { w: 35.0, e: 36.0, s: 30.9, n: 33.3 };

const BATCH = 100; // the API's hard limit per request
const PACE = 1100; // ms between calls — the endpoint allows one a second

const round = (n) => Math.round(n * 1e6) / 1e6;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchBatch(points) {
  const locations = points.map((p) => `${round(p.lat)},${round(p.lon)}`).join('|');
  const url = `https://api.opentopodata.org/v1/srtm90m?locations=${locations}`;
  for (let attempt = 0; ; attempt++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const { results } = await res.json();
      if (!Array.isArray(results) || results.length !== points.length) {
        throw new Error(`expected ${points.length} values, got ${results?.length}`);
      }
      return results.map((r) => r.elevation);
    } catch (err) {
      if (attempt >= 7) throw err;
      await sleep(Math.min(30_000, 2000 * 2 ** attempt));
    }
  }
}

const cells = [];
for (let j = 0; j < NY; j++) {
  for (let i = 0; i < NX; i++) {
    cells.push({ lon: BOUNDS.w + i * STEP, lat: BOUNDS.n - j * STEP });
  }
}

const batches = [];
for (let k = 0; k < cells.length; k += BATCH) batches.push(cells.slice(k, k + BATCH));

const dem = new Int16Array(cells.length);
for (let b = 0; b < batches.length; b++) {
  const started = Date.now();
  const values = await fetchBatch(batches[b]);
  values.forEach((metres, k) => {
    const { lon, lat } = batches[b][k];
    const inRift = lon >= RIFT.w && lon <= RIFT.e && lat >= RIFT.s && lat <= RIFT.n;
    const v = metres ?? 0;
    dem[b * BATCH + k] = Math.round(v < 0 && !inRift ? 1 : v);
  });
  console.log(`${b + 1}/${batches.length} batches`);
  await sleep(Math.max(0, PACE - (Date.now() - started)));
}

const b64 = Buffer.from(dem.buffer, dem.byteOffset, dem.byteLength).toString('base64');
writeFileSync(new URL('../app/dem.ts', import.meta.url), `\
// AUTO-GENERATED by scripts/build-dem.mjs — do not edit by hand.
// NASA SRTM 90 m elevations on a ${STEP}° grid, via the OpenTopoData API.

export const BOUNDS = { w: ${BOUNDS.w}, e: ${BOUNDS.e}, s: ${BOUNDS.s}, n: ${BOUNDS.n} };
export const DEM_NX = ${NX};
export const DEM_NY = ${NY};
const DEM_B64 = '${b64}';

function decode(b64: string): Int16Array {
  const bin = typeof atob === 'function' ? atob(b64) : Buffer.from(b64, 'base64').toString('binary');
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new Int16Array(bytes.buffer, bytes.byteOffset, bytes.byteLength >> 1);
}

/** Elevation in metres, row-major from the north-west corner. 0 means open water. */
export const DEM = decode(DEM_B64);
`);

let lo = Infinity;
let hi = -Infinity;
let sea = 0;
for (const v of dem) {
  if (v < lo) lo = v;
  if (v > hi) hi = v;
  if (v <= 0) sea++;
}
console.log(`app/dem.ts — ${NX}×${NY} = ${dem.length} nodes, ${lo}..${hi} m, ${(sea / dem.length * 100).toFixed(0)}% water`);
